---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rocky10
    image: docker.io/geerlingguy/docker-rockylinux10-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
